version: '3'
services:
  user-service:
    container_name: user-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:3000" ]
      interval: 30s
      timeout: 10s
      retries: 1
    volumes:
      - .:/app
    restart: always
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - rabbitmq
  notification-service:
    container_name: notification-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:3001" ]
      interval: 30s
      timeout: 10s
      retries: 1
    volumes:
      - .:/app
    restart: always
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'